### PR TITLE
use numpy

### PR DESCRIPTION
**Pull request by dchudz**
should be faster but we'll find out soon

### CODE REVIEW

**Comment by jeffkaufman** [comment]
David and I pair programmed this

**Comment by gwillen** [comment]
Hrm, could we coordinate a bit more in the future? (As much my fault as yours.) I had started working on this, and it seems we have now done a bunch of redundant work between us. :-\

**Comment by jeffkaufman** [comment]
sorry, I didn't realize that you were working on it too :(

**Comment by jeffkaufman** [comment]
It is much faster now: fast enough that I'm not able to meaningfully stress it with my existing stress testing program

**Pull request merged**
