### PR TITLE
Rebased version of 'event subsystem' by dspeyer

### PR DESCRIPTION
**Pull request by gwillen**
Rebase of #8. Work in progress (do not merge yet.) In particular, I haven't tested the WSGI stuff, and I probably have some of those bits wrong.

Also, it seems like the checked-in version of server.py doesn't run, so I'm not sure what the current version of that is. I added a commit that makes it run (and fixes some type stuff just to keep mypy happy, no significant changes there.)

### CODE REVIEW

**Comment by gwillen** [comment]
@dspeyer should probably take a look.

**Comment by dspeyer** [comment]
Looks good on a casual readthrough.

There's some type annotations squashed into here that don't seem related to
the event subsystem.  I don't actually care, just thought I should
mention.  Also, what's this type annotation system?  Is it any good?  But I
digress...

You've got a system for initializing events from a server side environment
variable?  Did I write that and forget about it?  I can't think of a use
case.  But it does no harm either.

I haven't tested it since I'm not clear on how one runs the server since
the uwsgi changes.  But if it worked for you, I expect it'll work in
general.  Nothing I'd expect to be brittle.

**Comment by gwillen** [comment]
The type annotation system is mypy, it is semi-official I guess? The annotations themselves are (as you can see) part of Python syntax, but python doesn't check them itself.

The commit with the type annotation fixes is separate and I should probably pull it out of this PR.

The environment variables are just how wsgi passes headers, as far as I can tell. This is meant to be a 1:1 port of the stuff you wrote.

**Comment by dspeyer** [comment]
Oh, right.  That makes sense now.  I should have noticed that was
new_events, not events.  I may be tired.

**Comment by jeffkaufman** [comment]
> Also, it seems like the checked-in version of server.py doesn't run, so I'm not sure what the current version of that is. I added a commit that makes it run (and fixes some type stuff just to keep mypy happy, no significant changes there.)

Thanks for cleaning this up!

**Comment by dspeyer** [comment]
Fixes thus far in the attempt of getting this working...

diff --git a/html/app.js b/html/app.js
index 9243c8d..f85cb29 100644
--- a/html/app.js
+++ b/html/app.js
@@ -101,6 +101,12 @@ function update_calendar() {
       let upcomingEvent = null;
       const now = Date.now();

+      if ( ! data.items ) {
+        // TODO: Save the error code?
+        lib.log(LOG_WARNING, "No data from Google Calendar");
+        return;
+      }
+
       data.items.forEach(item => {
         // If an event is currently happening we want to check whether
         // that's what people are here for. Similarly, if an event is
@@ -335,7 +341,7 @@ var alarms_fired = {};
 var cur_clock_cbs = [];

 export function declare_event(evid, offset) {
-  cur_clock_cbs.push( (clock)=>{
event_data.push({evid,clock:clock-(offset||0)*sample_rate}); } );
+  cur_clock_cbs.push( (clock)=>{
event_data.push({evid,clock:clock-(offset||0)*audioCtx.sampleRate}); } );
   playerNode.port.postMessage({
     type: "request_cur_clock"
   });
@@ -1030,7 +1036,7 @@ async function reload_settings(startup) {
 }

 export function init_events() {
-  let target_url = server_path + "reset_events";
+  let target_url = server_path_text.value + "reset_events";
   let xhr = new XMLHttpRequest();
   xhr.open("POST", target_url, true);
   xhr.send();
@@ -1227,13 +1233,15 @@ async function handle_message(event) {
     return;
   } else if (msg.type == "alarm") {
     if ((msg.time in alarms) && ! (msg.time in alarms_fired)) {
+      lib.log(LOG_INFO,"calling alarm at "+msg.time)
       alarms[msg.time]();
-      alarms_fired[msg.time] = True;
+      alarms_fired[msg.time] = true;
     }
     return;
   } else if (msg.type == "cur_clock") {
     for (let cb of cur_clock_cbs) {
       cb(msg.clock);
+      lib.log(LOG_WARNING, "got clock "+msg.clock+" and event_data is now
"+event_data);
     }
     cur_clock_cbs = [];
     return
diff --git a/html/index.html b/html/index.html
index cedfc98..65ace39 100644
--- a/html/index.html
+++ b/html/index.html
@@ -1,4 +1,5 @@
 <html>
+<head>
 <title>"Bucket Brigade" Audio Demo</title>
 <style>
 body {
@@ -141,7 +142,8 @@ body {
   padding: 1em;
 }
 </style>
-
+<link rel=stylesheet href=lyrics.css>
+</head>

 <h1>Bucket Brigade Singing</h1>
 <div id=currentEvent>loading...</div>
diff --git a/html/lyrics.js b/html/lyrics.js
index b3f0205..58e378e 100644
--- a/html/lyrics.js
+++ b/html/lyrics.js
@@ -1,4 +1,7 @@
 import { start_hooks, stop_hooks, event_hooks, declare_event, init_events
} from './app.js';
+import * as lib from './lib.js';
+import {LOG_VERYSPAM, LOG_SPAM, LOG_DEBUG, LOG_INFO, LOG_WARNING,
LOG_ERROR} from './lib.js';
+

 let lyrics = "Hands chip the |flint, light the |fire, skin the
|kill\n|Feet move the |tribe track the |herd with a |will \nHuman-|kind
|struggles, on the |edge of histo |ry\n|Time to settle |down, time to
|grow, time to |bree|eed..\n|Plow tills the |soil, plants the |seed, pray
for |rain\n|Scythe reaps the | wheat, to the |mill, to grind the
|grain\n|Towns.. and.. |cities spread to |empire over-|night\n|Hands keep
|building as we |chant the ancient |rite...".split('|');

@@ -62,7 +65,11 @@ button.addEventListener("mousedown", ()=>{
 });

 event_hooks.push( (lid)=>{
+    lib.log(LOG_INFO, "event hook invoked "+lid);
     if (spans[lid]) {
         spans[lid].className='lyrics heard';
+        lib.log(LOG_INFO, "colored span "+lid);
+    } else {
+        lib.log(LOG_INFO, "no span "+lid);
     }
 });
diff --git a/server.py b/server.py
index 9766559..cca9d29 100755
--- a/server.py
+++ b/server.py
@@ -615,7 +615,7 @@ def do_OPTIONS(environ, start_response) ->
Iterable[bytes]:
     start_response(
         '200 OK',
         [("Access-Control-Allow-Origin", "*"),
-         ("Access-Control-Allow-Headers", "Content-Type")])
+         ("Access-Control-Allow-Headers", "Content-Type, X-Event-Data")])
     return b'',

 def do_GET(environ, start_response) -> Iterable[bytes]:
@@ -625,7 +625,7 @@ def do_GET(environ, start_response) -> Iterable[bytes]:
     start_response(
         '200 OK',
         [("Access-Control-Allow-Origin", "*"),
-         ("Access-Control-Allow-Headers", "Content-Type"),
+         ("Access-Control-Allow-Headers", "Content-Type, X-Event-Data"),
          ("Access-Control-Expose-Headers", "X-Audio-Metadata"),
          ("X-Audio-Metadata", json.dumps({
              "server_clock": server_clock,
@@ -671,7 +671,7 @@ def do_POST(environ, start_response) -> Iterable[bytes]:
     start_response(
         '200 OK',
         [("Access-Control-Allow-Origin", "*"),
-         ("Access-Control-Allow-Headers", "Content-Type"),
+         ("Access-Control-Allow-Headers", "Content-Type, X-Event-Data"),
          ("Access-Control-Expose-Headers", "X-Audio-Metadata"),
          ("X-Audio-Metadata", x_audio_metadata),
          ("Content-Type", "application/octet-stream")])

**Comment by gwillen** [comment]
cherry-picked changes from c4609bb01ae752ab8657d50cbeca63fe63bb94df, which I think should be the same as the patch you posted.

**Comment by gwillen** [comment]
Ok, since the lyrics UI is a placeholder anyway (as are the lyrics displayed), and we don't want to mess up the existing bucket brigade app, I have just wrapped the lyrics ui in a `div` with `display:none` for now.

I pulled the type stuff out of this PR and pushed it into master (but github seems confused about that and is still displaying it with this PR, I suspect harmlessly.)

I also rebased this PR up to current master.

I _think_ at this point it's safe to merge this (I will do one more test first to make sure the bucket brigade app still seems to work fine with this addition.)

**Pull request merged**
